# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest   
    
    steps:    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'dotnet build $(buildConfiguration)'    
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        buildContext: '$(Build.SourcesDirectory)/matcrm.api/'
        dockerfile: '$(Build.SourcesDirectory)/matcrm.api/Dockerfile'
        tags: |
          $(tag)
