# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  oneclappapi:
    image: oneclappapi
    build:
      context: .
      dockerfile: matcrm.api/Dockerfile
    ports:
      - 8081:8081
